CREATE TABLE TBL_CHARACTERS (
	ID INTEGER,
	NAME VARCHAR(20),
	DIET VARCHAR(20),
	SOUNDS VARCHAR(20)
);

INSERT INTO TBL_CHARACTERS VALUES (1,'zombies','brains', 'Graargh');
INSERT INTO TBL_CHARACTERS VALUES (2,'pirates','rum','Aye Aye, Matey' );
INSERT INTO TBL_CHARACTERS VALUES (3,'vampires','blood','Scream');
INSERT INTO TBL_CHARACTERS VALUES (4,'ninjas','rice','Sssh');

SELECT NAME,DIET,SOUNDS FROM TBL_CHARACTERS;

DROP TABLE TBL_COMMENTS;

CREATE TABLE TBL_COMMENTS (
	ID INTEGER UNIQUE NOT NULL AUTO_INCREMENT,
	PRIMARY KEY(ID),
	MVCHAR_ID INTEGER NOT NULL,
	MVCHAR_NAME VARCHAR(20) NOT NULL,
	USERNAME VARCHAR(20) NOT NULL,
	COMMENT_DATE DATETIME,
	COMMENT LONGTEXT NOT NULL,
	FOREIGN KEY(MVCHAR_ID, MVCHAR_NAME) REFERENCES TBL_CHARACTERS(ID, NAME)
);

ALTER TABLE TBL_COMMENTS TYPE=InnoDB;

INSERT INTO TBL_COMMENTS VALUES (1,1,'zombies','2010-09-09 15:13:00','A zombie is a creature that appears in books, films and popular culture');

SELECT * FROM TBL_COMMENTS;

INSERT INTO TBL_COMMENTS values (3,'pirates','2010-09-09 16:13:00','Pirates are awesomely cool');