DROP TABLE TBL_COMMENTS;
DROP TABLE TBL_CHARACTERS;


CREATE TABLE TBL_CHARACTERS (
	MVCHAR_ID INTEGER CONSTRAINT MVCHAR_PK PRIMARY KEY,
	MVCHAR_NAME VARCHAR(20),
	DIET VARCHAR(20),
	SOUNDS VARCHAR(20)
);

CREATE TABLE TBL_COMMENTS (
	COMMENT_ID SMALLINT NOT NULL GENERATED ALWAYS AS IDENTITY,
	PRIMARY KEY(COMMENT_ID),
	MVCHAR_ID INTEGER CONSTRAINT CHAR_FK REFERENCES TBL_CHARACTERS,
	MVCHAR_NAME VARCHAR(20),
	USERNAME VARCHAR(20) NOT NULL,
	COMMENT_DATE DATE,
	COMMENT LONG VARCHAR NOT NULL
);
