SELECT * from TBL_CHARACTERS;
SELECT COUNT(*) FROM TBL_CHARACTERS WHERE MVCHAR_NAME = 'zombies';
SELECT MVCHAR_NAME,DIET,SOUNDS FROM TBL_CHARACTERS where MVCHAR_NAME = 'zombies';
SELECT * FROM TBL_COMMENTS;